name: Workflow .NET

on:
  push:
    branches:
      - main

    schedule:
      - cron: '0 * * * *'  # Executa a cada hora (minuto 0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
          echo "Restoring dependencies..."
          dotnet restore **/*.csproj

      - name: Build
        run: |
          echo "Compiling project..."
          dotnet build **/*.csproj --no-restore
      
      - name: Execute tiny script
        run: |
          echo "Checking Workflow..."
          date